### ISSUE TITLE
Relax require on permitted_attributes

### ISSUE THREAD

**Issue by eLod** [varvet/pundit#396] opened 2016-05-25 03:19 UTC
Occasionally i send some values into the form for the new action (typically for STI stuff, sending type). My code would do something like `Post.new permitted_attributes`, but it fails when i don't have any params. It is caused by `Pundit#permitted_attributes` doing `params.require(param_key)`. Would using `params.fetch(param_key, {})` be acceptable?

**Comment by jmera** [comment] 2016-06-10 11:21
@eLod I strongly suggest using strong parameters. I've had a similar issue where the behavior of `Pundit#permitted_attributes` didn't quite fit the needs of my application.  IMO it's a very generic method meant to cover a lot of use cases but is most definitely not a catch-all solution (neither do I think it's meant to be).

One way to go about dealing with your issue is, well, just override `permitted_attributes` wherever you need the custom behavior.  This is how I've dealt with the issue in the past.

**Comment by eLod** [comment] 2016-06-10 11:36
@jmera not sure if i understood you right, but Pundit itself is using strong parameters. it is a perfectly valid abstraction (your policy classes providing the list of attributes to whitelist, while the method in controller returns the actual params whitelisted with strong parameters), just there is a slight problem for my use case (using require of strong parameters). other libraries (like cancan) do use fetch the way i suggested. also i realize this may not be a very common use case, so i tried to use wording reflecting that in my original issue description.

**Comment by jmera** [comment] 2016-06-10 13:16
@eLod agreed, your description of how `Pundit#permitted_attributes` looks accurate to me—there is no disagreement there.

What I'm suggesting is: if that method doesn't work for you in a specific controller because it's using `params.require`, simply override it to fit your needs. Here's an example ([current implementation](https://github.com/elabs/pundit/blob/c3f2d/lib/pundit.rb#L238-L247)):

```ruby
class MyController < ApplicationController
  # ...
  def permitted_attributes(record, action = params[:action])
    param_key = PolicyFinder.new(record).param_key
    policy = policy(record)
    method_name = if policy.respond_to?("permitted_attributes_for_#{action}")
      "permitted_attributes_for_#{action}"
    else
      "permitted_attributes"
    end
    # Use fetch instead of require
    params.fetch(param_key, {}).permit(*policy.public_send(method_name))
  end
end
```

However if your argument is that the method implementation should use `fetch` rather than `require`, that's a different discussion.  Is that what you're suggesting?

**Comment by eLod** [comment] 2016-06-10 13:18
@jmera yes that is exactly my suggestion.

**Comment by jrgns** [comment] 2016-07-26 13:48
Is there a specific reason for using `require` rather than `fetch`? I use pundit mostly in a non rails environment, and `require` isn't available on Hashes there. Which means I have to implement this functionality myself.

I'd much rather just centralize this in the pundit policies.

**Comment by md5** [comment] 2016-08-18 17:01
FYI, this has already been discussed in https://github.com/elabs/pundit/issues/298

**Comment by jnicklas** [comment] 2016-11-04 12:23
I don't think #298 is quite the same issue. To me this suggestion seems pretty reasonable. It's not often where you need to set an empty attributes hash, but it does happen on occasion, and I don't see any reason not to support it.

**Comment by jmera** [comment] 2016-11-17 05:34
Hmm, I think the current behavior is pretty useful. Sometimes we want to enforce the param key is being used. Perhaps give two options: `permitted_attributes` => no exception, uses fetch; `permitted_attributes!` => throws exception, `.require`s param key.

**Comment by pablocrivella** [comment] 2018-03-09 08:07
Another approach that could be taken to make this easier to override is described on this issue:

https://github.com/varvet/pundit/issues/469 (possible duplicate of this one?)

**Comment by Linuus** [comment] 2018-05-15 19:48
@jmera does your code actually work when the param key is not found?

```ruby
params.fetch(param_key, {}).permit(*policy.public_send(method_name))
```

`.fetch` would return the empty hash and then you run `.permit` on it which doesn’t exist, right?

**Closed** 2018-05-17 18:08 UTC
Labels: enhancement
