### ISSUE TITLE
module naming clash between rails and policy with subject array

### ISSUE THREAD

**Issue by gagalago** [varvet/pundit#531] opened 2018-06-21 14:44 UTC
I have naming conflicts in this context:
```ruby
# models
class Agency < ApplicationRecord
  has_many :opportunities, inverse_of: :agency
end
class Opportunity < ApplicationRecord
  has_one :agency, inverse_of: :opportunities
  has_many :metadata, as: :metadatable, dependent: :destroy
end
class Metadatum < ApplicationRecord
  belongs_to :metadatable, polymorphic: true
end
# policies
class Agency::Opportunity::MetadatumPolicy < NamespacedPolicy
  def show?
    user.can?("read...")
  end
end
```
with that context, when I perform `Agency.first.opportunities` I have this error: `undefined method '_reflect_on_association' for Agency::Opportunity:Module`

I use Rails 5.1.4

A solution can be to pluralize modules in the `Pundit::PolicyFinder#find`.

What do you think?

**Comment by Linuus** [comment] 2018-06-21 16:45
Does this have anything to do with pundit really? Isn’t this just a result of Ruby’s weird constant lookup?

**Comment by gagalago** [comment] 2018-06-22 09:09
Yes and not. 
The problem is that when I want to check `authorization [@agency, @opporutnity, @metadatum]` (with all instance variables as active record), I need to create the policy `Agency::Opportunity::MetadatumPolicy` to follow the pundit convention (`Pundit::PolicyFinder#find`). But as you said, this also create all intermediary modules that create a wrong constant lookup for a future call to an association.

Unless I am wrong, when you look for `table_name`, that is some Rails related stuff. so I think that changing only that to be more compatible with Rails is not a big deal.

To solve that, I propose to pluralize `table_name` when we look for policies so that the policy will be `Agencies::Opportunities::MetadatumPolicy`.

**Comment by Linuus** [comment] 2018-06-22 09:22
Just pass symbols instead of instance variables.

`authorize [:agencies, :opportunities, @metadatum]`

If you do that you have full control of the namespace.

**Comment by gagalago** [comment] 2018-06-22 10:02
I can do that but 
- if resources are polymorphic that add some unneeded complexity to the controller to convert it to a symbol
- with a symbol, I can't have access to these resources in the policy

**Comment by gagalago** [comment] 2018-06-22 12:47
yes, for the moment I use the rubygems version (1.1).

For the removing of the namespace, I also comment that pull request #529 to express my point of view about this removing.
I expose a way to have the subject in the same way as you propose in that pull request but also the possibility to have namespace and all of that with minimal modifications.
I understand that most of the time the namespace is not useful (and maybe also anoying) into the policy but removing it completely is a bit overreacting.

Solution when the only difference is to add  `*namespace,` into the constructor of `ApplicationPolicy`:
```
class ApplicationPolicy
  def initialize(user, *namespace, subject)
    @user = user
    @namespace = namespace # can be removed if you don't care about namespace
    @subject = subject
  end
end
```

**Comment by Linuus** [comment] 2018-07-03 10:56
Why do you even need namespacing in your examples? To me it looks like you are only using namespacing because you want to pass multiple objects which is not how you are supposed to use it.

Namespacing is more intended to be used for cases where, for instance, you have an Admin namespace and you want to pass the same `Article` to different policies (`Admin::ArticlePolicy` and `ArticlePolicy`). Then you can do `authorize [:admin, @article]`. The other solution to this would be to have separate objects, `Admin::Article` and `Article` which would pick up the correct policy as automatically.

**Comment by gagalago** [comment] 2018-07-03 12:41
I understand your point of view. But I didn't understand why you want to enforce it.

I namespace policies with the same structure as I nest routes and all that I need is all the resources of the current route in the right order. So an array of objects is exactly what I need to find the right policy and as arguments that I need.
I love the actual implementation that allows me to find the right policy, just by knowing which route was used and allowing me to use all resources expressed in that route.

I don't understand why you want to force that I create an object to encapsulate, as I will need to create one different class for each policy with nested resources and this class will be used only by the policy. If I have to do that, my codebase will become more difficult to understand as always I will need to read code from 2 classes (policy + encapsulation).

Maybe you can explain to me why, in the past, you used an array and inferring module name with `table_name`. That can help me to understand why now you don't want it anymore.

**Comment by Linuus** [comment] 2018-07-04 18:12
> I namespace policies with the same structure as I nest routes

Generally I don't think it makes sense to do that. Perhaps it does in your case though, I don't know (I'm not saying that you are doing something wrong here), but I don't think Pundit should encourage it. Also, Pundit can't accomodate _all_ use cases. It's more of a set of conventions and it won't fit _everyone_.

> I don't understand why you want to force that I create an object to encapsulate, as I will need to create one different class for each policy with nested resources and this class will be used only by the policy.

Well, it's your choice to only use it in the policy. Why not use it everywhere? :)
The reason we are removing this... "feature" is because it's weird as it is now when used as intended (`[:admin, @object]` style). Sure, we could implement a workaround as you suggested but I still don't think that's a good API to have, and I don't want to maintain an API that I don't believe is good.

> Maybe you can explain to me why, in the past, you used an array and inferring module name with `table_name`. That can help me to understand why now you don't want it anymore.

When was `table_name` used? I was not the maintainer whenever that was and I can't answer for their choices. Sorry.


Also, in your first example, you have access to all objects you need through the associations on `Metadatum`. There is no need to pass them all into the policy.

**Comment by gagalago** [comment] 2018-07-05 06:20
Thanks for the explanation. It's more clear to me in which direction Pundit want to go :+1: and I aggree with it.

just one more things:

> Also, in your first example, you have access to all objects you need through the associations on Metadatum. There is no need to pass them all into the policy.

this is true for instance action, but for for scope it's more difficult to retrieve associated resources. So, maybe that's last things that's not clear to me is how to manage it. When I do `authorize [@agency, @agency.opportunities]` how can I retrieve the agency of the opportunity scope?

**Comment by gagalago** [comment] 2018-07-06 15:48
yes, some resources are polymorphic and that case will be the only place where I will need to create a domain object.

Thanks a lot for clarifying how to use in the right way Pundit. I will follow your suggestions. 

You can either close this issue or let it open if someone else wants to propose another way to use Pundit in that specific case.

**Comment by Linuus** [comment] 2018-07-06 16:05
No problem! It’s good to hear about different use cases for future development!

I’ll close the issue for now.

Thanks!

**Closed by Linuus** 2018-07-06 16:05 UTC
