### ISSUE TITLE
A permitted_attributes behavior change

### ISSUE THREAD

**Issue by pharmmd-rich** [varvet/pundit#469] opened 2017-07-03 16:36 UTC
The `permitted_attributes` method looks like the following:

```
  def permitted_attributes(record, action = params[:action])
    param_key = PolicyFinder.new(record).param_key
    policy = policy(record)
    method_name = if policy.respond_to?("permitted_attributes_for_#{action}")
      "permitted_attributes_for_#{action}"
    else
      "permitted_attributes"
    end
    params.require(param_key).permit(*policy.public_send(method_name))
  end
```

IMO this code is a bit inflexible.  For starters, the code automatically performs a `params.require`.  In pretty much every job I've worked at, we've had cases where we don't use `params.require`, but instead we use `params.permit` or `params.fetch`.  What do you guys think about my recommended changes below:

1.  Add a 3rd parameter, an options hash.
2. Add an options for `require: false` to the options hash.  If require is false, the `require(param_key)` doesn't get executed.
3. Add an option for `fetch: true` and `fetch_params` to the options hash.  If set, then `fetch` would get called with the specified params.
4.  Add a `param_key` option to the options hash to override the `param_key`.

This helps `permitted_attributes` cover the majority of scenarios.  Any thoughts?  If nobody has the bandwidth to tackle this I'd be willing to take a shot at a PR as soon as I have a moment of free time...assuming you all find these changes acceptable?

**Comment by pablocrivella** [comment] 2018-03-09 07:58
@pharmmd-rich On almost all my projects i have overriden this method like this:

```ruby
def permitted_attributes(record, action = params[:action])
  param_key = Pundit::PolicyFinder.new(record).param_key
  policy = policy(record)
  method_name =
    if policy.respond_to?("permitted_attributes_for_#{action}")
      "permitted_attributes_for_#{action}"
    else
      'permitted_attributes'
    end
  params.fetch(param_key, {}).permit(policy.public_send(method_name))
end
```

And i would be really nice if we could just override the params fetching part.

Maybe if we had change the method like this:
```ruby
def permitted_attributes(record, action = params[:action])
  policy = policy(record)
  method_name =
    if policy.respond_to?("permitted_attributes_for_#{action}")
      "permitted_attributes_for_#{action}"
    else
      'permitted_attributes'
    end
  pundit_params_for(record).permit(policy.public_send(method_name))
end

def pundit_params_for(record)
  param_key = Pundit::PolicyFinder.new(record).param_key
  params.require(param_key)
end
```

We could easily override it according to the project needs:

```ruby
def pundit_params_for(record)
  param_key = Pundit::PolicyFinder.new(record).param_key
  params.fetch(param_key, {})
end


# or i.e. if using jsonapi-spec

def pundit_params_for(_record)
  params.fetch(:data, {}).fetch(:attributes)
end
```

**Comment by Linuus** [comment] 2018-05-02 20:42
Duplicate of #396

**Closed by Linuus** 2018-05-02 20:42 UTC
Labels: duplicate
